import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#f8fafc' },
  container: { padding: 20, gap: 16 },
  title: { fontSize: 28, fontWeight: '800', color: '#0f172a' },
  subtitle: { fontSize: 14, color: '#64748b' },
  card: { backgroundColor: '#ffffff', borderRadius: 20, padding: 18, gap: 10, shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 10, elevation: 2 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  label: { fontSize: 14, color: '#64748b' },
  amount: { fontSize: 26, fontWeight: '800', color: '#0f172a' },
  smallAmount: { fontSize: 17, fontWeight: '800', color: '#0f172a' },
  button: { backgroundColor: '#2563eb', borderRadius: 14, padding: 14, alignItems: 'center' },
  buttonText: { color: '#ffffff', fontWeight: '800', fontSize: 16 },
  secondaryButton: { borderColor: '#cbd5e1', borderWidth: 1, borderRadius: 14, padding: 12, alignItems: 'center', backgroundColor: '#ffffff' },
  selectedButton: { backgroundColor: '#dbeafe', borderColor: '#2563eb' },
  secondaryButtonText: { color: '#0f172a', fontWeight: '700' },
  chip: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: '#e2e8f0' },
  chipSelected: { backgroundColor: '#bfdbfe' },
  chipText: { fontSize: 13, fontWeight: '700', color: '#334155' },
  badge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999, backgroundColor: '#e0f2fe' },
  badgeShared: { backgroundColor: '#fef3c7' },
  badgeText: { fontSize: 12, fontWeight: '800', color: '#0f172a' },
  input: { backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 14, paddingHorizontal: 14, paddingVertical: 12, fontSize: 16 },
  sectionTitle: { fontSize: 18, fontWeight: '800', color: '#0f172a' },
  error: { color: '#dc2626', fontWeight: '700' },
});
